branches:
  only:
    - /^\d+\.\d+\.\d+(-[A-Za-z-]+(\.\d+)?)?$/

language: node_js
node_js:
  - "7"

sudo: false

os:
#  - osx
  - linux

cache:
  directories:
    - node_modules
  yarn: true

notifications:
  email:
    on_success: never

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - node --version
  - npm --version
  - git submodule init
  - git submodule update
  - yarn --ignore-scripts

script:
  - npm run build
