branches:
  only:
    # - /^\d+\.\d+\.\d+(-[A-Za-z-]+(\.\d+)?)?$/

language: node_js
node_js:
  - "7"

matrix:
  include:
    - os: linux
      sudo: false
      env: TARGET_ARCH=x64
    - os: linux
      sudo: false
      env: TARGET_ARCH=x86
    - os: osx
      sudo: false
      env: TARGET_ARCH=x64

cache:
  directories:
    - node_modules
  yarn: true

notifications:
  email:
    on_success: never

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - node --version
  - npm --version
  - yarn --ignore-scripts

before_script:
  - npm run compile
  - npm run build

script:
  - npm run test

after_success:
  - npm run upload
