image: Visual Studio 2015

environment:
  matrix:
  - TARGET_ARCH: x86
  - TARGET_ARCH: x64

before_build:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%'

build_script:
  - npm run build
