image: Visual Studio 2015

environment:
  matrix:
  - TARGET_ARCH: x86
  - TARGET_ARCH: x64
  YACC: win_bison

install:
  - choco install winflexbison3
  - node --version
  - npm --version
  - git submodule init
  - git submodule update
  - yarn --ignore-scripts
  - tsc --version

before_build:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%'

build_script:
  - npm run build
