image: Visual Studio 2015

skip_non_tags: true

environment:
  matrix:
  - TARGET_ARCH: x86
  - TARGET_ARCH: x64
  YACC: win_bison

cache:
  - node_modules
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - ps: Install-Product node 7.9.0 x64
  - npm install -g npm@4 --silent
  - choco install winflexbison3
  - node --version
  - npm --version
  - git submodule init
  - git submodule update
  - yarn --ignore-scripts

before_build:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %TARGET_ARCH%'

build_script:
  - npm run compile
  - npm run build

test_script:
  # - npm run test

deploy_script:
  - npm run upload
